# Azure resource group deployment
# Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'demoarm'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'devqa'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://github.com/1sagarshinde/filestore/blob/master/staticwebside.json'
    deploymentMode: 'Incremental'